# BetterChunkLoaders
# Version 1.0.4
# If a player is offline more than this number of hours at server start, his chunk loaders won't be loaded
MaxHoursOffline: 168

# Default amount of chunks for all players
DefaultChunksAmount:
  AlwaysOn: 5
  OnlineOnly: 50

# Max amount of chunks for each player
MaxChunksAmount:
  AlwaysOn: 50
  OnlineOnly: 150

# Chunk Loaders block types ID:Metadata or ID
alwaysOnBlockId: 57
onlineOnlyBlockId: 42
  
# Data Store to use, XML or MySQL, but extensions can add custom data stores
DataStore: XML

# Configuration for MySQL Data Store
MySQL:
  Hostname: localhost
  Username: BetterChunkLoader
  Password: BetterPassword
  Database: BetterChunkLoader
  